/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface InheritXInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelPlan"
      | "checkIn"
      | "claim"
      | "claimDirect"
      | "confidentialProtocolId"
      | "createPlan"
      | "createPlanDirect"
      | "getEthLockedHandle"
      | "getHeirStatus"
      | "getOwnerPlans"
      | "getPlan"
      | "getPlanBalance"
      | "kycStatus"
      | "kycVerifiers"
      | "owner"
      | "ownerPlans"
      | "planCount"
      | "plans"
      | "renounceOwnership"
      | "setKYCVerifier"
      | "setVaultNote"
      | "submitKYC"
      | "timeUntilTrigger"
      | "transferOwnership"
      | "trigger"
      | "verifyKYC"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CheckIn"
      | "InheritanceClaimed"
      | "KYCSubmitted"
      | "KYCVerified"
      | "OwnershipTransferred"
      | "PlanCancelled"
      | "PlanCreated"
      | "PlanTriggered"
      | "PublicDecryptionVerified"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelPlan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkIn",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [BigNumberish, BigNumberish, BytesLike[], BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimDirect",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createPlan",
    values: [
      BigNumberish,
      string,
      string,
      BytesLike[],
      BytesLike[],
      BytesLike[],
      BytesLike[],
      BytesLike[],
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createPlanDirect",
    values: [
      BigNumberish,
      string,
      string,
      AddressLike[],
      BigNumberish[],
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getEthLockedHandle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHeirStatus",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerPlans",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlanBalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "kycStatus",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "kycVerifiers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerPlans",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "planCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "plans", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setKYCVerifier",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setVaultNote",
    values: [
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(functionFragment: "submitKYC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "timeUntilTrigger",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trigger",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyKYC",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "cancelPlan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "checkIn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimDirect",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createPlan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createPlanDirect",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEthLockedHandle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHeirStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerPlans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPlan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPlanBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "kycStatus", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "kycVerifiers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ownerPlans", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "planCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "plans", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setKYCVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVaultNote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitKYC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "timeUntilTrigger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "trigger", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifyKYC", data: BytesLike): Result;
}

export namespace CheckInEvent {
  export type InputTuple = [
    planId: BigNumberish,
    owner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [planId: bigint, owner: string, timestamp: bigint];
  export interface OutputObject {
    planId: bigint;
    owner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InheritanceClaimedEvent {
  export type InputTuple = [
    planId: BigNumberish,
    beneficiaryIndex: BigNumberish,
    claimer: AddressLike
  ];
  export type OutputTuple = [
    planId: bigint,
    beneficiaryIndex: bigint,
    claimer: string
  ];
  export interface OutputObject {
    planId: bigint;
    beneficiaryIndex: bigint;
    claimer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KYCSubmittedEvent {
  export type InputTuple = [wallet: AddressLike];
  export type OutputTuple = [wallet: string];
  export interface OutputObject {
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace KYCVerifiedEvent {
  export type InputTuple = [wallet: AddressLike];
  export type OutputTuple = [wallet: string];
  export interface OutputObject {
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlanCancelledEvent {
  export type InputTuple = [planId: BigNumberish];
  export type OutputTuple = [planId: bigint];
  export interface OutputObject {
    planId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlanCreatedEvent {
  export type InputTuple = [
    planId: BigNumberish,
    owner: AddressLike,
    planType: BigNumberish,
    name: string
  ];
  export type OutputTuple = [
    planId: bigint,
    owner: string,
    planType: bigint,
    name: string
  ];
  export interface OutputObject {
    planId: bigint;
    owner: string;
    planType: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlanTriggeredEvent {
  export type InputTuple = [planId: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [planId: bigint, timestamp: bigint];
  export interface OutputObject {
    planId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PublicDecryptionVerifiedEvent {
  export type InputTuple = [
    handlesList: BytesLike[],
    abiEncodedCleartexts: BytesLike
  ];
  export type OutputTuple = [
    handlesList: string[],
    abiEncodedCleartexts: string
  ];
  export interface OutputObject {
    handlesList: string[];
    abiEncodedCleartexts: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InheritX extends BaseContract {
  connect(runner?: ContractRunner | null): InheritX;
  waitForDeployment(): Promise<this>;

  interface: InheritXInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelPlan: TypedContractMethod<[planId: BigNumberish], [void], "nonpayable">;

  checkIn: TypedContractMethod<[planId: BigNumberish], [void], "nonpayable">;

  claim: TypedContractMethod<
    [
      planId: BigNumberish,
      beneficiaryIndex: BigNumberish,
      handlesList: BytesLike[],
      abiEncodedCleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  claimDirect: TypedContractMethod<
    [planId: BigNumberish],
    [void],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createPlan: TypedContractMethod<
    [
      planType: BigNumberish,
      planName: string,
      planDescription: string,
      encHeirAddrs: BytesLike[],
      encShares: BytesLike[],
      inputProofsAddrs: BytesLike[],
      inputProofsShares: BytesLike[],
      heirAddressHashes: BytesLike[],
      inactivityDays: BigNumberish,
      unlockDate: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  createPlanDirect: TypedContractMethod<
    [
      planType: BigNumberish,
      planName: string,
      planDescription: string,
      heirAddrs: AddressLike[],
      shareBps: BigNumberish[],
      inactivityDays: BigNumberish,
      unlockDate: BigNumberish
    ],
    [bigint],
    "payable"
  >;

  getEthLockedHandle: TypedContractMethod<
    [planId: BigNumberish],
    [string],
    "view"
  >;

  getHeirStatus: TypedContractMethod<
    [planId: BigNumberish, wallet: AddressLike],
    [bigint],
    "view"
  >;

  getOwnerPlans: TypedContractMethod<[owner: AddressLike], [bigint[]], "view">;

  getPlan: TypedContractMethod<
    [planId: BigNumberish],
    [
      [
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean
      ] & {
        owner_: string;
        planType_: bigint;
        name_: string;
        description_: string;
        lastCheckin_: bigint;
        inactivityDays_: bigint;
        unlockDate_: bigint;
        beneficiaryCount_: bigint;
        triggered_: boolean;
        claimed_: boolean;
        cancelled_: boolean;
      }
    ],
    "view"
  >;

  getPlanBalance: TypedContractMethod<[planId: BigNumberish], [bigint], "view">;

  kycStatus: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  kycVerifiers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  ownerPlans: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  planCount: TypedContractMethod<[], [bigint], "view">;

  plans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        boolean,
        boolean,
        boolean
      ] & {
        owner: string;
        planType: bigint;
        name: string;
        description: string;
        lastCheckin: bigint;
        inactivityDays: bigint;
        unlockDate: bigint;
        ethLocked: string;
        beneficiaryCount: bigint;
        triggered: boolean;
        claimed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setKYCVerifier: TypedContractMethod<
    [verifier: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  setVaultNote: TypedContractMethod<
    [
      planId: BigNumberish,
      beneficiaryIndex: BigNumberish,
      encNote1: BytesLike,
      encNote2: BytesLike,
      proof1: BytesLike,
      proof2: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  submitKYC: TypedContractMethod<[], [void], "nonpayable">;

  timeUntilTrigger: TypedContractMethod<
    [planId: BigNumberish],
    [bigint],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  trigger: TypedContractMethod<[planId: BigNumberish], [void], "nonpayable">;

  verifyKYC: TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelPlan"
  ): TypedContractMethod<[planId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "checkIn"
  ): TypedContractMethod<[planId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<
    [
      planId: BigNumberish,
      beneficiaryIndex: BigNumberish,
      handlesList: BytesLike[],
      abiEncodedCleartexts: BytesLike,
      decryptionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimDirect"
  ): TypedContractMethod<[planId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createPlan"
  ): TypedContractMethod<
    [
      planType: BigNumberish,
      planName: string,
      planDescription: string,
      encHeirAddrs: BytesLike[],
      encShares: BytesLike[],
      inputProofsAddrs: BytesLike[],
      inputProofsShares: BytesLike[],
      heirAddressHashes: BytesLike[],
      inactivityDays: BigNumberish,
      unlockDate: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "createPlanDirect"
  ): TypedContractMethod<
    [
      planType: BigNumberish,
      planName: string,
      planDescription: string,
      heirAddrs: AddressLike[],
      shareBps: BigNumberish[],
      inactivityDays: BigNumberish,
      unlockDate: BigNumberish
    ],
    [bigint],
    "payable"
  >;
  getFunction(
    nameOrSignature: "getEthLockedHandle"
  ): TypedContractMethod<[planId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getHeirStatus"
  ): TypedContractMethod<
    [planId: BigNumberish, wallet: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOwnerPlans"
  ): TypedContractMethod<[owner: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getPlan"
  ): TypedContractMethod<
    [planId: BigNumberish],
    [
      [
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean
      ] & {
        owner_: string;
        planType_: bigint;
        name_: string;
        description_: string;
        lastCheckin_: bigint;
        inactivityDays_: bigint;
        unlockDate_: bigint;
        beneficiaryCount_: bigint;
        triggered_: boolean;
        claimed_: boolean;
        cancelled_: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlanBalance"
  ): TypedContractMethod<[planId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "kycStatus"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "kycVerifiers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerPlans"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "planCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "plans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        boolean,
        boolean,
        boolean
      ] & {
        owner: string;
        planType: bigint;
        name: string;
        description: string;
        lastCheckin: bigint;
        inactivityDays: bigint;
        unlockDate: bigint;
        ethLocked: string;
        beneficiaryCount: bigint;
        triggered: boolean;
        claimed: boolean;
        cancelled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setKYCVerifier"
  ): TypedContractMethod<
    [verifier: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVaultNote"
  ): TypedContractMethod<
    [
      planId: BigNumberish,
      beneficiaryIndex: BigNumberish,
      encNote1: BytesLike,
      encNote2: BytesLike,
      proof1: BytesLike,
      proof2: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitKYC"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "timeUntilTrigger"
  ): TypedContractMethod<[planId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trigger"
  ): TypedContractMethod<[planId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifyKYC"
  ): TypedContractMethod<[wallet: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CheckIn"
  ): TypedContractEvent<
    CheckInEvent.InputTuple,
    CheckInEvent.OutputTuple,
    CheckInEvent.OutputObject
  >;
  getEvent(
    key: "InheritanceClaimed"
  ): TypedContractEvent<
    InheritanceClaimedEvent.InputTuple,
    InheritanceClaimedEvent.OutputTuple,
    InheritanceClaimedEvent.OutputObject
  >;
  getEvent(
    key: "KYCSubmitted"
  ): TypedContractEvent<
    KYCSubmittedEvent.InputTuple,
    KYCSubmittedEvent.OutputTuple,
    KYCSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "KYCVerified"
  ): TypedContractEvent<
    KYCVerifiedEvent.InputTuple,
    KYCVerifiedEvent.OutputTuple,
    KYCVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PlanCancelled"
  ): TypedContractEvent<
    PlanCancelledEvent.InputTuple,
    PlanCancelledEvent.OutputTuple,
    PlanCancelledEvent.OutputObject
  >;
  getEvent(
    key: "PlanCreated"
  ): TypedContractEvent<
    PlanCreatedEvent.InputTuple,
    PlanCreatedEvent.OutputTuple,
    PlanCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PlanTriggered"
  ): TypedContractEvent<
    PlanTriggeredEvent.InputTuple,
    PlanTriggeredEvent.OutputTuple,
    PlanTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "PublicDecryptionVerified"
  ): TypedContractEvent<
    PublicDecryptionVerifiedEvent.InputTuple,
    PublicDecryptionVerifiedEvent.OutputTuple,
    PublicDecryptionVerifiedEvent.OutputObject
  >;

  filters: {
    "CheckIn(uint256,address,uint256)": TypedContractEvent<
      CheckInEvent.InputTuple,
      CheckInEvent.OutputTuple,
      CheckInEvent.OutputObject
    >;
    CheckIn: TypedContractEvent<
      CheckInEvent.InputTuple,
      CheckInEvent.OutputTuple,
      CheckInEvent.OutputObject
    >;

    "InheritanceClaimed(uint256,uint8,address)": TypedContractEvent<
      InheritanceClaimedEvent.InputTuple,
      InheritanceClaimedEvent.OutputTuple,
      InheritanceClaimedEvent.OutputObject
    >;
    InheritanceClaimed: TypedContractEvent<
      InheritanceClaimedEvent.InputTuple,
      InheritanceClaimedEvent.OutputTuple,
      InheritanceClaimedEvent.OutputObject
    >;

    "KYCSubmitted(address)": TypedContractEvent<
      KYCSubmittedEvent.InputTuple,
      KYCSubmittedEvent.OutputTuple,
      KYCSubmittedEvent.OutputObject
    >;
    KYCSubmitted: TypedContractEvent<
      KYCSubmittedEvent.InputTuple,
      KYCSubmittedEvent.OutputTuple,
      KYCSubmittedEvent.OutputObject
    >;

    "KYCVerified(address)": TypedContractEvent<
      KYCVerifiedEvent.InputTuple,
      KYCVerifiedEvent.OutputTuple,
      KYCVerifiedEvent.OutputObject
    >;
    KYCVerified: TypedContractEvent<
      KYCVerifiedEvent.InputTuple,
      KYCVerifiedEvent.OutputTuple,
      KYCVerifiedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PlanCancelled(uint256)": TypedContractEvent<
      PlanCancelledEvent.InputTuple,
      PlanCancelledEvent.OutputTuple,
      PlanCancelledEvent.OutputObject
    >;
    PlanCancelled: TypedContractEvent<
      PlanCancelledEvent.InputTuple,
      PlanCancelledEvent.OutputTuple,
      PlanCancelledEvent.OutputObject
    >;

    "PlanCreated(uint256,address,uint8,string)": TypedContractEvent<
      PlanCreatedEvent.InputTuple,
      PlanCreatedEvent.OutputTuple,
      PlanCreatedEvent.OutputObject
    >;
    PlanCreated: TypedContractEvent<
      PlanCreatedEvent.InputTuple,
      PlanCreatedEvent.OutputTuple,
      PlanCreatedEvent.OutputObject
    >;

    "PlanTriggered(uint256,uint256)": TypedContractEvent<
      PlanTriggeredEvent.InputTuple,
      PlanTriggeredEvent.OutputTuple,
      PlanTriggeredEvent.OutputObject
    >;
    PlanTriggered: TypedContractEvent<
      PlanTriggeredEvent.InputTuple,
      PlanTriggeredEvent.OutputTuple,
      PlanTriggeredEvent.OutputObject
    >;

    "PublicDecryptionVerified(bytes32[],bytes)": TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;
    PublicDecryptionVerified: TypedContractEvent<
      PublicDecryptionVerifiedEvent.InputTuple,
      PublicDecryptionVerifiedEvent.OutputTuple,
      PublicDecryptionVerifiedEvent.OutputObject
    >;
  };
}
